package th.ac.ku.kps.eng.cpe.soa.driveCar.model;
// Generated Apr 27, 2019 4:05:42 PM by Hibernate Tools 5.3.6.Final

import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;

import com.fasterxml.jackson.annotation.JsonBackReference;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonManagedReference;

/**
 * Car generated by hbm2java
 */
public class Car implements java.io.Serializable {

	private Integer carId;
	@JsonIgnoreProperties({"hibernateLazyInitializer", "handler"})
	@ManyToOne(fetch=FetchType.LAZY,cascade = CascadeType.ALL)
	@JoinColumn(name = "province_id", nullable = false)
	@JsonManagedReference
	private Province provinceByAddressProvince;
	@JsonIgnoreProperties({"hibernateLazyInitializer", "handler"})
	@ManyToOne(fetch=FetchType.LAZY,cascade = CascadeType.ALL)
	@JoinColumn(name = "province_id", nullable = false)
	@JsonManagedReference
	private Province provinceByProvinceId;
	private String licensePlate;
	private String model;
	private int seatCount;
	private String typeCar;
	private String brand;
	private double price;
	private Integer discount;
	@JsonBackReference
	private Set rents = new HashSet(0);

	public Car() {
	}

	public Car(String licensePlate, String model,int seatCount, String typeCar, String brand, double price) {
		this.licensePlate = licensePlate;
		this.model = model;
		this.seatCount = seatCount;
		this.typeCar = typeCar;
		this.brand = brand;
		this.price = price;
	}

	public Car(Province provinceByAddressProvince, Province provinceByProvinceId, String licensePlate, int seatCount,
			String typeCar, String brand, double price, Integer discount, Set rents) {
		this.provinceByAddressProvince = provinceByAddressProvince;
		this.provinceByProvinceId = provinceByProvinceId;
		this.licensePlate = licensePlate;
		this.seatCount = seatCount;
		this.typeCar = typeCar;
		this.brand = brand;
		this.price = price;
		this.discount = discount;
		this.rents = rents;
	}

	public Integer getCarId() {
		return this.carId;
	}

	public void setCarId(Integer carId) {
		this.carId = carId;
	}

	public Province getProvinceByAddressProvince() {
		return this.provinceByAddressProvince;
	}

	public void setProvinceByAddressProvince(Province provinceByAddressProvince) {
		this.provinceByAddressProvince = provinceByAddressProvince;
	}

	public Province getProvinceByProvinceId() {
		return this.provinceByProvinceId;
	}

	public void setProvinceByProvinceId(Province provinceByProvinceId) {
		this.provinceByProvinceId = provinceByProvinceId;
	}

	public String getLicensePlate() {
		return this.licensePlate;
	}

	public void setLicensePlate(String licensePlate) {
		this.licensePlate = licensePlate;
	}

	public int getSeatCount() {
		return this.seatCount;
	}

	public void setSeatCount(int seatCount) {
		this.seatCount = seatCount;
	}

	public String getTypeCar() {
		return this.typeCar;
	}

	public void setTypeCar(String typeCar) {
		this.typeCar = typeCar;
	}

	public String getBrand() {
		return this.brand;
	}

	public void setBrand(String brand) {
		this.brand = brand;
	}

	public double getPrice() {
		return this.price;
	}

	public void setPrice(double price) {
		this.price = price;
	}

	public Integer getDiscount() {
		return this.discount;
	}

	public void setDiscount(Integer discount) {
		this.discount = discount;
	}

	public Set getRents() {
		return this.rents;
	}

	public void setRents(Set rents) {
		this.rents = rents;
	}

	public String getModel() {
		return model;
	}

	public void setModel(String model) {
		this.model = model;
	}

}
