package th.ac.ku.kps.eng.cpe.soa.driveCar.model;
// Generated Apr 29, 2019 2:16:44 PM by Hibernate Tools 5.3.6.Final

import java.util.HashSet;
import java.util.Set;

import com.fasterxml.jackson.annotation.JsonBackReference;

/**
 * Province generated by hbm2java
 */
public class Province implements java.io.Serializable {

	private int provinceId;
	private String name;
	@JsonBackReference
	private Set carsForAddressProvince = new HashSet(0);
	@JsonBackReference
	private Set carsForProvinceId = new HashSet(0);

	public Province() {
	}

	public Province(int provinceId, String name) {
		this.provinceId = provinceId;
		this.name = name;
	}

	public Province(int provinceId, String name, Set carsForAddressProvince, Set carsForProvinceId) {
		this.provinceId = provinceId;
		this.name = name;
		this.carsForAddressProvince = carsForAddressProvince;
		this.carsForProvinceId = carsForProvinceId;
	}

	public int getProvinceId() {
		return this.provinceId;
	}

	public void setProvinceId(int provinceId) {
		this.provinceId = provinceId;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Set getCarsForAddressProvince() {
		return this.carsForAddressProvince;
	}

	public void setCarsForAddressProvince(Set carsForAddressProvince) {
		this.carsForAddressProvince = carsForAddressProvince;
	}

	public Set getCarsForProvinceId() {
		return this.carsForProvinceId;
	}

	public void setCarsForProvinceId(Set carsForProvinceId) {
		this.carsForProvinceId = carsForProvinceId;
	}

}
